version: '3'
services:
  db:
    container_name: movie
    image: mysql:5.7
    ports:
      - "30001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      
  app:
    container_name: MovieBooking
    links:
      - 'db'
    build: ./
    ports:
      - '5001:5000'